[[account]]
name = "keykekk"
cookie = "a2lsZXJva2VyMkBtYWlsLnJ1OmNoYWluYm95MjAwNA"

# EXAMPLE:
# [[account]]
# name = "testaccount1"
# cookie = "auth=authcookie_; twoFactorAuth="
# proxy = "socks5://10.124.0.1:1080" # (OPTIONAL)
# You can add multiple accounts to the config.

[group]
name = "keykekk chillout"
id = "KEYKEK.2650"

# EXAMPLE:
# [group]
# name = "testgroup1"
# id = "grp_"
# You can only have one group.
